apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lottery-service.fullname" . }}
  labels:
    {{- include "lottery-service.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "lottery-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lottery-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /lng
              port: 8080
          readinessProbe:
            httpGet:
              path: /lng
              port: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
