apiVersion: v1
kind: Service
metadata:
  name: {{ include "lottery-service.fullname" . }}
  labels:
    {{- include "lottery-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "lottery-service.selectorLabels" . | nindent 4 }}
